title: Edward Quadtree talks tech
description: >- # ignore newlines until "baseurl:"
baseurl: "" 
url: "https://edward-quadtree.github.io" 
theme: minima 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Include these settings if they are missing
collections:
  posts:
    output: true
